### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[74fe834](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/74fe834e449f38b4da7e90283ddfba1f212b7a90)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[74fe834](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/74fe834e449f38b4da7e90283ddfba1f212b7a90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-686) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C9%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912091105005493-686%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r7NkV50WSLpdOE3QMqefSgtcKENEZKaKtB34mK8raJE%3D&st=2019-12-09T11%3A00%3A58Z&se=2020-01-09T11%3A05%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[e9aab79](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/e9aab794e65d5bcd80ec8499c69106057386e7cd)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[e9aab79](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/e9aab794e65d5bcd80ec8499c69106057386e7cd)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C9%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912091107058689-686%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hbx0qboqfuRhWt1D5Phsf1IXV0oxt58tR3Wm47gXUB4%3D&st=2019-12-09T11%3A02%3A53Z&se=2020-01-09T11%3A07%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
