### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[7201815](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/7201815cb516cf960474c64091e10eac5a3dc05c)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[7201815](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/7201815cb516cf960474c64091e10eac5a3dc05c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-429) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C1%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912011102500145-429%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cIcWSM3T0oJ%2Bv%2Bao%2FA%2BZ7NNJKnUxaOK1sSxIXXF67TE%3D&st=2019-12-01T10%3A58%3A31Z&se=2020-01-01T11%3A03%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[70b0d97](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/70b0d9730fd4d2db1075e26f2e2fae44e1eb9ad5)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[70b0d97](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/70b0d9730fd4d2db1075e26f2e2fae44e1eb9ad5)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C1%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912011103457688-429%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cL5AstDtm6HNtpnwT8wHDAuu52OqQIOerRraGgJA5qM%3D&st=2019-12-01T10%3A59%3A25Z&se=2020-01-01T11%3A04%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
