### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[83aa49d](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/83aa49d22cae895ebbbc40630d287da58947518a)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[83aa49d](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/83aa49d22cae895ebbbc40630d287da58947518a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-192) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C21%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911211205330401-192%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HO46ca8nwRQ5DMH5tZ5LDAXFGy848Omk1vyNQWctYpU%3D&st=2019-11-21T12%3A01%3A13Z&se=2019-12-22T12%3A06%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[da17923](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/da179237c24d910804cd7a86153b39c42f2b6a3f)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[da17923](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/da179237c24d910804cd7a86153b39c42f2b6a3f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C21%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911211206309716-192%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8PGSbA4%2F0vhkqu4wZet%2F%2BTB4Sfi7w6DM5086ZxBYRJ0%3D&st=2019-11-21T12%3A02%3A20Z&se=2019-12-22T12%3A07%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
