### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[1364083](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1364083ad182a38d0fa5386f9c8855c7b020210e)_: 

:clock10: **Pending**: waiting for processors ([13](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1364083](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1364083ad182a38d0fa5386f9c8855c7b020210e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-3489) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202004130758345928-3489%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vksiulIGYQG%2FoDTUgJdsorWDvafYkB9Bi9hV%2FlQI5No%3D&st=2020-04-13T07%3A54%3A05Z&se=2020-05-14T07%3A59%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[921f479](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/921f47985197c9cabb79f2142cc50418f5d83bc8)_: 

:clock10: **Pending**: waiting for processors ([13](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[921f479](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/921f47985197c9cabb79f2142cc50418f5d83bc8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202004130759383588-3489%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TQEjFGtlQykTl08ocLwQWDkeZnA%2FP3fHcdgcgFkEMgk%3D&st=2020-04-13T07%3A55%3A16Z&se=2020-05-14T08%3A00%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
