### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[78c62d6](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/78c62d618a93ca654e5b50ab45966e6f80c29fad)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[78c62d6](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/78c62d618a93ca654e5b50ab45966e6f80c29fad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-280) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C26%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911261104014953-280%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=92k0QrYfhZYcrUm1JsuJRQIZvmO%2FetaictjWqsizmqI%3D&st=2019-11-26T10%3A59%3A51Z&se=2019-12-27T11%3A04%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[27e6877](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/27e6877c433aadbbb214d089aec3655823fff253)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[27e6877](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/27e6877c433aadbbb214d089aec3655823fff253)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C26%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911261105137412-280%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kP%2BIdIHIlIKUVDd2QYRbifBCKjVkAYd5bcJvlgIeCgo%3D&st=2019-11-26T11%3A01%3A14Z&se=2019-12-27T11%3A06%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
