### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[e843f28](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/e843f28c59ea5d79c352e23dbdd9decf8a01f828)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[e843f28](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/e843f28c59ea5d79c352e23dbdd9decf8a01f828)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C15%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911150643053987-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a%2FAxE04nmCi7h3vx4auFSeLTu8rVAUN6oT1%2FVIbmF6E%3D&st=2019-11-15T06%3A38%3A40Z&se=2019-12-16T06%3A43%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[ce7b601](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ce7b601a053d06d0578909df0e060665b8f19c18)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[ce7b601](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ce7b601a053d06d0578909df0e060665b8f19c18)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C15%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911150644132049-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q4iuw2a002QoAYZtOmsHvPS3lAT1gNQSARlgQrIJwPE%3D&st=2019-11-15T06%3A39%3A46Z&se=2019-12-16T06%3A44%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
