### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[bf0dc99](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/bf0dc990d8486d69586939a952159dc25e05aa32)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[bf0dc99](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/bf0dc990d8486d69586939a952159dc25e05aa32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-565) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C5%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912050600409867-565%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GSpRHTspqhXEBtIiw1yd2LT3%2BPHwsWlOvvI3mZSy8Xc%3D&st=2019-12-05T05%3A56%3A25Z&se=2020-01-05T06%3A01%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[a2d7518](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/a2d751831af960e94da18c663efba8be3d4218c6)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[a2d7518](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/a2d751831af960e94da18c663efba8be3d4218c6)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C5%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912050601479495-565%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dcv1MPFKn1%2Fn8EwPB6YhaRd2Q5fpH7g8BSjANYUO%2Few%3D&st=2019-12-05T05%3A57%3A34Z&se=2020-01-05T06%3A02%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
