### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[8a85a8a](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/8a85a8a7ca295adc3b131d023b9873ee0aabde4b)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[8a85a8a](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/8a85a8a7ca295adc3b131d023b9873ee0aabde4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-2707) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C25%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202002252119238476-2707%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p07ZU6EHjsokKyeGmEn1%2BXzM7j2ZWtAVWuSkOCNAvSI%3D&st=2020-02-25T21%3A15%3A01Z&se=2020-03-27T21%3A20%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[c29aab1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/c29aab1eb20b2cc2b434d484adb51d9e8fba85ae)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[c29aab1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/c29aab1eb20b2cc2b434d484adb51d9e8fba85ae)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C25%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202002252120271921-2707%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PpxYI%2BPU6vmx75wbHopgIpA11Avl8io%2FxB%2FIzBx5BLA%3D&st=2020-02-25T21%3A16%3A04Z&se=2020-03-27T21%3A21%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
