### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[ff0faa1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ff0faa1b6af0d7c04ee40dbdf111f9587bf6ea6d)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[ff0faa1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ff0faa1b6af0d7c04ee40dbdf111f9587bf6ea6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-1776) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C28%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202001281105304363-1776%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4KfqWpyDl1KuR9QHurUW4vTFcdXiOy5hQLbG0E8mzSU%3D&st=2020-01-28T11%3A01%3A27Z&se=2020-02-28T11%3A06%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[d4d6f60](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d4d6f60d8e442a65b38029fefc94c6604a55c0a8)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[d4d6f60](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d4d6f60d8e442a65b38029fefc94c6604a55c0a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-31ff877d)

<a id="31ff877d"></a>
###
 - **Line 0**: **[Error]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`.This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com).This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C28%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202001281106339800-1776%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oYW8eSfsTVX%2FRLg1jHOVWcVBbJdir8LtlWwSeEb7Tgs%3D&st=2020-01-28T11%3A02%3A05Z&se=2020-02-28T11%3A07%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
