### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[61e6857](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/61e685785ca22b66f8df91539f144e4353ee0f95)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[61e6857](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/61e685785ca22b66f8df91539f144e4353ee0f95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-706) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C10%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912101204388456-706%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M%2FTYF9BPCu%2B5o%2BbUSKuBi2OXoVvGJ6AJAkuS318F7bk%3D&st=2019-12-10T12%3A00%3A18Z&se=2020-01-10T12%3A05%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[bb25294](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/bb25294bd97d7ed03a4887ecdba9d083594d4a44)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[bb25294](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/bb25294bd97d7ed03a4887ecdba9d083594d4a44)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C10%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912101205539219-706%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G4FkoBSi2a0Ksd2dyHpTTMcZ7dLhZPFHetvEnWGTB7Y%3D&st=2019-12-10T12%3A01%3A36Z&se=2020-01-10T12%3A06%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
