### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[96abb1e](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/96abb1e49886a4ad962a34634144e5e044427783)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[96abb1e](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/96abb1e49886a4ad962a34634144e5e044427783)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-998) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912231105169410-998%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mMLjKe1kKmycI%2FkKUNXCcmLxF7OxOPNqwT%2Fsgbd%2FeTU%3D&st=2019-12-23T11%3A01%3A02Z&se=2020-01-23T11%3A06%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[5d1b257](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/5d1b257254fcabdd2a7d73b36bbd1ae9bb336c43)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[5d1b257](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/5d1b257254fcabdd2a7d73b36bbd1ae9bb336c43)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912231106198795-998%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rGfP2YHE8glUnC8eMUZrh63rC01PfwgB%2FNtgrsTZ9Ew%3D&st=2019-12-23T11%3A02%3A03Z&se=2020-01-23T11%3A07%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
