### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[d4f2504](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d4f250486053f71a3f8e6b8aae452d062c0e37ce)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[d4f2504](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d4f250486053f71a3f8e6b8aae452d062c0e37ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-3165) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202003232123112907-3165%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9loZOsSM31K0q1bBF9B09duAC%2Fl%2F%2FsQMn5wa4yT%2BA3I%3D&st=2020-03-23T21%3A18%3A45Z&se=2020-04-23T21%3A23%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[2b4cd52](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/2b4cd52e7e96e178241fc85f68054084a6ddefb7)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[2b4cd52](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/2b4cd52e7e96e178241fc85f68054084a6ddefb7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C3%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202003232124142201-3165%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mVxZQ4Zsv9Zc%2FIYaKPNbGvo8y61nTZ6FLPUWO0OyWkY%3D&st=2020-03-23T21%3A20%3A29Z&se=2020-04-23T21%3A25%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
