### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[6011c22](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/6011c22d365b701848388e0fbb31b166559aa10e)_: 

:clock10: **Pending**: waiting for processors ([30](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 30 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[6011c22](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/6011c22d365b701848388e0fbb31b166559aa10e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-4013) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C11%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202005112126285749-4013%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VwrlcYARg9OmnRj8x0D2%2B6%2B7FCZRCchCnD7NwwNnV%2FY%3D&st=2020-05-11T21%3A22%3A14Z&se=2020-06-11T21%3A27%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[ba05b0d](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ba05b0d7dd2fb5a8d3e0601463ff68c638578f0b)_: 

:clock10: **Pending**: waiting for processors ([30](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 30 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[ba05b0d](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/ba05b0d7dd2fb5a8d3e0601463ff68c638578f0b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C11%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202005112127320319-4013%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O29NjPY2WqIWVtUULApHK2bjZ1JtS7k5%2F9bWDzQGGgo%3D&st=2020-05-11T21%3A23%3A18Z&se=2020-06-11T21%3A28%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
