### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[94a7120](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/94a712064068baeff1c0fa809c43251c5a785fa5)_: 

:clock10: **Pending**: waiting for processors ([64](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 64 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[94a7120](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/94a712064068baeff1c0fa809c43251c5a785fa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-796) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C13%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912130110306197-796%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FwBL2%2FH4sfGXgW6pr%2B6UvH%2F9REiHYeBiTN4AfQv2cRQ%3D&st=2019-12-13T01%3A06%3A07Z&se=2020-01-13T01%3A11%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[5581803](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/5581803096a397c69c338b0747710804ee33b1ec)_: 

:clock10: **Pending**: waiting for processors ([64](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 64 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[5581803](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/5581803096a397c69c338b0747710804ee33b1ec)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C13%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912130111368408-796%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bZCH2biY3x%2FcpEhmdayKsnH3n%2BXfK3H0U%2F5VJZbkqk0%3D&st=2019-12-13T01%3A07%3A11Z&se=2020-01-13T01%3A12%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
