### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[a653511](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/a6535114274672b1b2598d567868c42423849922)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[a653511](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/a6535114274672b1b2598d567868c42423849922)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-300) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C27%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911270122365371-300%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HmxU3N7Rkpzoja1EqlgRFubeYMMp12y415UP4veXYpI%3D&st=2019-11-27T01%3A18%3A36Z&se=2019-12-28T01%3A23%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[97c19e4](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/97c19e496064972acba62bb4bb56a35dddac7130)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[97c19e4](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/97c19e496064972acba62bb4bb56a35dddac7130)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C27%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911270123454231-300%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f%2BnYU1HaDahblYNjfUrV5f4nyHkNCnxd9SUHXyWBukc%3D&st=2019-11-27T01%3A19%3A35Z&se=2019-12-28T01%3A24%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
