### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[be4867f](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/be4867fcf6a5567ed27b7cee77e606fca07098fa)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[be4867f](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/be4867fcf6a5567ed27b7cee77e606fca07098fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-125) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C19%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911190126388001-125%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aOaAeiACHkvMzpqNvU%2FmavkjQpT8wRJ3mv%2Fv1bwrCms%3D&st=2019-11-19T01%3A22%3A38Z&se=2019-12-20T01%3A27%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[1af8357](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1af835796dd09b189fb74f0b839955ba99dff1ed)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[1af8357](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1af835796dd09b189fb74f0b839955ba99dff1ed)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C19%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911190128459426-125%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V9J26KAQJCNfC8wq8%2B3SmOvP0m7t7vvz7O%2BXP980kHM%3D&st=2019-11-19T01%3A24%3A22Z&se=2019-12-20T01%3A29%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
