### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[876fe4a](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/876fe4ae98e785fa5901511e0ee76fc6cea59b3e)_: 

:clock10: **Pending**: waiting for processors ([23](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 23 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[876fe4a](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/876fe4ae98e785fa5901511e0ee76fc6cea59b3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Prod_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/incrementalpr-addresource.jpg?branch=pr-en-us-4790) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202006232322268671-4790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e6VDLWBA4zEdzq3mODusdF6YnsXhtSskiUzkGaBWj%2F4%3D&st=2020-06-23T23%3A17%3A54Z&se=2020-07-24T23%3A22%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/af4743a4-ec8b-7f8c-52b9-90904ecb627f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[32ea8d3](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/32ea8d3114971c204ac3b9861803f8c659e9825c)_: 

:clock10: **Pending**: waiting for processors ([22](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 22 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[32ea8d3](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/32ea8d3114971c204ac3b9861803f8c659e9825c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C23%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C202006232323298825-4790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5R1r8hMkOVU%2FwfxOMywWrZDCsUy4vEO3o0CnegCjH6k%3D&st=2020-06-23T23%3A18%3A58Z&se=2020-07-24T23%3A23%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/af4743a4-ec8b-7f8c-52b9-90904ecb627f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
