### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[d1f5542](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d1f55423cd2609f4275b251269fdb06f9ed201a0)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[d1f5542](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/d1f55423cd2609f4275b251269fdb06f9ed201a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-478) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C3%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912030123448550-478%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ah9bFLzMucpeuFQOTeibLTwrrJTgVrbMs4lM99Yg9kw%3D&st=2019-12-03T01%3A19%3A34Z&se=2020-01-03T01%3A24%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[6a57517](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/6a5751734d548b8aa6c12347ddf1bc070698cc67)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[6a57517](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/6a5751734d548b8aa6c12347ddf1bc070698cc67)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C3%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201912030124480397-478%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2MxaW9vVxfhaAcXEjL0CfjqfFgOzujf3FoeOqRxiF4s%3D&st=2019-12-03T01%3A20%3A24Z&se=2020-01-03T01%3A25%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
