### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1ba1edb](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1ba1edb3ed8d4dd9f72686beada394affda2582e)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1ba1edb](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/1ba1edb3ed8d4dd9f72686beada394affda2582e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Prod_Dynamic/addcontent.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Prod_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic-v3/addcontent?branch=pr-en-us-387) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C28%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911280050114143-387%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w4Ae%2Fkn2jSTnKtOfSDPyB1NWqBjGGef2ZjGD0DRjYPs%3D&st=2019-11-28T00%3A45%3A51Z&se=2019-12-29T00%3A50%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[50429e2](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/50429e27f3c88b1d024bc4f143a27d4fc2913946)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[50429e2](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic-v3/commits/50429e27f3c88b1d024bc4f143a27d4fc2913946)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C28%5Caf4743a4-ec8b-7f8c-52b9-90904ecb627f%5CPullRequest%5C201911280051107694-387%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uB081f54lpTAfP33kz1kmjFJ9CJLNrBblFM0Hc0FRv4%3D&st=2019-11-28T00%3A46%3A53Z&se=2019-12-29T00%3A51%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
